services:
  - type: web
    name: travelyx-kiosk-planb
    env: node
    plan: free
    rootDir: travelyx-backend
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 10000
